[build]
  publish = "."
  command = "echo 'No build step needed - static HTML deployment'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "echo 'Starting development server'"
  port = 8888
  publish = "."
